"""Add Case and MedicalImage tables.

Revision ID: 1a2b3c4d5e6f
Revises:
Create Date: 2025-08-02 12:00:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1a2b3c4d5e6f"
down_revision = "7f6982a53f57"
branch_labels = None
depends_on = None


def upgrade():
    """Apply the database migration to add Case and MedicalImage tables."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("case_date", sa.DateTime(), nullable=True),
        sa.Column("doctor_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_patient_id"), "cases", ["patient_id"], unique=False)
    op.create_table(
        "medical_images",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("case_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("image_path", sa.String(), nullable=False),
        sa.Column("upload_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """Revert the database migration by dropping medical_images and cases tables."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table("medical_images")
    op.drop_index(op.f("ix_cases_patient_id"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
